var namespaceannis_1_1gui =
[
    [ "beans", "namespaceannis_1_1gui_1_1beans.html", "namespaceannis_1_1gui_1_1beans" ],
    [ "controlpanel", "namespaceannis_1_1gui_1_1controlpanel.html", "namespaceannis_1_1gui_1_1controlpanel" ],
    [ "exporter", "namespaceannis_1_1gui_1_1exporter.html", "namespaceannis_1_1gui_1_1exporter" ],
    [ "media", "namespaceannis_1_1gui_1_1media.html", "namespaceannis_1_1gui_1_1media" ],
    [ "paging", "namespaceannis_1_1gui_1_1paging.html", "namespaceannis_1_1gui_1_1paging" ],
    [ "querybuilder", "namespaceannis_1_1gui_1_1querybuilder.html", "namespaceannis_1_1gui_1_1querybuilder" ],
    [ "resultview", "namespaceannis_1_1gui_1_1resultview.html", "namespaceannis_1_1gui_1_1resultview" ],
    [ "servlets", "namespaceannis_1_1gui_1_1servlets.html", "namespaceannis_1_1gui_1_1servlets" ],
    [ "tutorial", "namespaceannis_1_1gui_1_1tutorial.html", "namespaceannis_1_1gui_1_1tutorial" ],
    [ "visualizers", "namespaceannis_1_1gui_1_1visualizers.html", "namespaceannis_1_1gui_1_1visualizers" ],
    [ "widgets", "namespaceannis_1_1gui_1_1widgets.html", "namespaceannis_1_1gui_1_1widgets" ],
    [ "AboutPanel", "classannis_1_1gui_1_1AboutPanel.html", "classannis_1_1gui_1_1AboutPanel" ],
    [ "CitationLinkGenerator", "classannis_1_1gui_1_1CitationLinkGenerator.html", "classannis_1_1gui_1_1CitationLinkGenerator" ],
    [ "CitationWindow", "classannis_1_1gui_1_1CitationWindow.html", "classannis_1_1gui_1_1CitationWindow" ],
    [ "CorpusBrowserPanel", "classannis_1_1gui_1_1CorpusBrowserPanel.html", "classannis_1_1gui_1_1CorpusBrowserPanel" ],
    [ "Helper", "classannis_1_1gui_1_1Helper.html", "classannis_1_1gui_1_1Helper" ],
    [ "HelpUsPanel", "classannis_1_1gui_1_1HelpUsPanel.html", "classannis_1_1gui_1_1HelpUsPanel" ],
    [ "HistoryPanel", "classannis_1_1gui_1_1HistoryPanel.html", "classannis_1_1gui_1_1HistoryPanel" ],
    [ "ImagePanel", "classannis_1_1gui_1_1ImagePanel.html", "classannis_1_1gui_1_1ImagePanel" ],
    [ "MainApp", "classannis_1_1gui_1_1MainApp.html", "classannis_1_1gui_1_1MainApp" ],
    [ "MatchedNodeColors", "enumannis_1_1gui_1_1MatchedNodeColors.html", "enumannis_1_1gui_1_1MatchedNodeColors" ],
    [ "MetaDataPanel", "classannis_1_1gui_1_1MetaDataPanel.html", "classannis_1_1gui_1_1MetaDataPanel" ],
    [ "PluginSystem", "interfaceannis_1_1gui_1_1PluginSystem.html", "interfaceannis_1_1gui_1_1PluginSystem" ],
    [ "ReportBugPanel", "classannis_1_1gui_1_1ReportBugPanel.html", "classannis_1_1gui_1_1ReportBugPanel" ],
    [ "SearchWindow", "classannis_1_1gui_1_1SearchWindow.html", "classannis_1_1gui_1_1SearchWindow" ],
    [ "CorpusSet", "classannis_1_1gui_1_1CorpusSet.html", "classannis_1_1gui_1_1CorpusSet" ],
    [ "InstanceConfig", "classannis_1_1gui_1_1InstanceConfig.html", "classannis_1_1gui_1_1InstanceConfig" ],
    [ "VisualizationToggle", "interfaceannis_1_1gui_1_1VisualizationToggle.html", "interfaceannis_1_1gui_1_1VisualizationToggle" ]
];