var namespaceannis =
[
    [ "administration", "namespaceannis_1_1administration.html", "namespaceannis_1_1administration" ],
    [ "corpuspathsearch", "namespaceannis_1_1corpuspathsearch.html", "namespaceannis_1_1corpuspathsearch" ],
    [ "dao", "namespaceannis_1_1dao.html", "namespaceannis_1_1dao" ],
    [ "exceptions", "namespaceannis_1_1exceptions.html", "namespaceannis_1_1exceptions" ],
    [ "gui", "namespaceannis_1_1gui.html", "namespaceannis_1_1gui" ],
    [ "libgui", "namespaceannis_1_1libgui.html", "namespaceannis_1_1libgui" ],
    [ "model", "namespaceannis_1_1model.html", "namespaceannis_1_1model" ],
    [ "provider", "namespaceannis_1_1provider.html", "namespaceannis_1_1provider" ],
    [ "ql", "namespaceannis_1_1ql.html", "namespaceannis_1_1ql" ],
    [ "resolver", "namespaceannis_1_1resolver.html", "namespaceannis_1_1resolver" ],
    [ "rest", "namespaceannis_1_1rest.html", "namespaceannis_1_1rest" ],
    [ "security", "namespaceannis_1_1security.html", "namespaceannis_1_1security" ],
    [ "service", "namespaceannis_1_1service.html", "namespaceannis_1_1service" ],
    [ "sqlgen", "namespaceannis_1_1sqlgen.html", "namespaceannis_1_1sqlgen" ],
    [ "utils", "namespaceannis_1_1utils.html", "namespaceannis_1_1utils" ],
    [ "visualizers", "namespaceannis_1_1visualizers.html", "namespaceannis_1_1visualizers" ],
    [ "CommonHelper", "classannis_1_1CommonHelper.html", "classannis_1_1CommonHelper" ],
    [ "CoveredTextsCalculator", "classannis_1_1CoveredTextsCalculator.html", "classannis_1_1CoveredTextsCalculator" ],
    [ "AnnisBaseRunner", "classannis_1_1AnnisBaseRunner.html", "classannis_1_1AnnisBaseRunner" ],
    [ "AnnisRunner", "classannis_1_1AnnisRunner.html", "classannis_1_1AnnisRunner" ],
    [ "AnnisRunnerException", "classannis_1_1AnnisRunnerException.html", "classannis_1_1AnnisRunnerException" ],
    [ "AnnisXmlContextHelper", "classannis_1_1AnnisXmlContextHelper.html", "classannis_1_1AnnisXmlContextHelper" ],
    [ "FindHelper", "classannis_1_1FindHelper.html", null ],
    [ "MemoryUsage", "classannis_1_1MemoryUsage.html", "classannis_1_1MemoryUsage" ],
    [ "TableFormatter", "classannis_1_1TableFormatter.html", "classannis_1_1TableFormatter" ],
    [ "UsageException", "classannis_1_1UsageException.html", "classannis_1_1UsageException" ],
    [ "WekaHelper", "classannis_1_1WekaHelper.html", "classannis_1_1WekaHelper" ]
];