var classannis_1_1gui_1_1AutoGeneratedQueries_1_1ShowCorpusBrowser =
[
    [ "generateCell", "classannis_1_1gui_1_1AutoGeneratedQueries_1_1ShowCorpusBrowser.html#ac157e87e22bf050a6c18d389531f6fe8", null ]
];